language: android
jdk:
  - oraclejdk8
android:
  components:
    - tools
    - platform-tools
    - build-tools-28.0.3
    - android-28
    - platforms-android-28
jobs:
  include:
    - name: Assemble
      script: ./gradlew assemble
    - name: Kotlin linter
      script: ./gradlew ktlint
    - name: Unit tests
      script: ./gradlew :OCast:test
script:
  - ./gradlew clean assemble ktlint :OCast:test
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache
