name: build
on: [push, pull_request]
defaults:
  run:
    shell: bash
jobs:
  assemble:
    runs-on: ubuntu-latest
    name: Assemble
    steps:
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - run: ./gradlew assemble
  verification:
    runs-on: ubuntu-latest
    needs: assemble
    strategy:
      matrix:
        parameters:
          - { job-name: 'Kotlin linter', gradle-command: './gradlew ktlint' }
          - { job-name: 'Java linter', gradle-command: './gradlew checkstyleMain' }
          - { job-name: 'Unit tests', gradle-command: './gradlew :sdk:test' }
    name: ${{ matrix.parameters.job-name }}
    steps:
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - run: ${{ matrix.parameters.gradle-command }}
